# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('district', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('contact_page', models.URLField()),
                ('person_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('title_long', models.CharField(max_length=100)),
                ('office_addr', models.CharField(max_length=256)),
                ('party', models.CharField(max_length=32)),
                ('twitter_username', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('district', models.IntegerField()),
            ],
        ),
    ]
