# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_page',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='office_addr',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='title_long',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
