# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0002_auto_20161113_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
