# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0004_auto_20161113_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(db_index=True, max_length=2, null=True),
        ),
    ]
